# Generated by Django 5.2.1 on 2025-06-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fone',
            new_name='phone',
        ),
    ]
