# Generated by Django 5.2.1 on 2025-06-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_rename_fist_name_contact_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='categry',
            new_name='category',
        ),
    ]
